### ISSUE TITLE
'segLight' was not declared in this scope on line 79

### ISSUE THREAD

**Issue by mattncsu** [scottcove/FastLED-7segment#1]
Tried compiling in Arduino but get subject error

**Comment by scottcove** [comment]
As discussed on the reddit thread, this is due to the ld_endPixel defined in the segLight function, as this is a carryover from some modifications I made before publishing the code.

**Comment by scottcove** [comment]
@mattncsu can you test and confirm the issue is resolved for you?

**Comment by mattncsu** [comment]
There's also an `ld_beginPixel` that I caught on line 85, after correcting those, my next error is on line 203: `    fill_solid( testStrip, LEDS_PER_DIGIT, CHSV(c,255,128) );`

```
exit status 1
no matching function for call to 'fill_solid(CRGB [4][21], const byte&, CHSV)'
```

**Comment by scottcove** [comment]
@mattncsu Apologies for the delay, I've been away from a compiler for a number of days.  Boy, oh Boy have I learnt the hard way not to publish unverified code.  I have now verified that the code compiles, but am not near my physical digits to test for a few more days.  I have committed the changes, regardless.  Feel free to test and report back.

**Comment by mattncsu** [comment]
No problem! I'll test it out later and let you know

**Comment by mattncsu** [comment]
It works!  Thanks again!
